// STYLES //
import "./globals.css";

// COMPONENTS //
import { Inter } from "next/font/google";

// DATA //
import type { Metadata } from "next";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Renders the root application layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={interSans.variable}>
      <body className="antialiased font-sans min-h-screen bg-n-100">
        {children}
      </body>
    </html>
  );
}
